# 📊 Pandas EAD 2 - Manipulação de Dados

Este notebook aborda técnicas avançadas de manipulação de dados com Pandas.

## 📚 Conceitos abordados:
- Filtros e seleção condicional
- Ordenação de dados
- Agrupamento (groupby)
- Junção de DataFrames (merge/join)
- Tratamento de dados faltantes
- Aplicação de funções

## 🎯 Objetivo:
Ao final deste módulo, você será capaz de manipular, filtrar e transformar dados usando Pandas.

**Vamos começar!** 🚀

## 1. Criando um DataFrame de Exemplo

Vamos criar um DataFrame com dados de vendas de uma loja:

In [12]:
import pandas as pd
import numpy as np

# Dados de vendas
dados_vendas = {
    'Produto': ['Notebook', 'Mouse', 'Teclado', 'Monitor', 'Headset', 
                'Notebook', 'Mouse', 'Teclado', 'Monitor', 'Headset'],
    'Vendedor': ['Ana', 'João', 'Ana', 'João', 'Maria', 
                 'Maria', 'Ana', 'João', 'Maria', 'Ana'],
    'Quantidade': [5, 10, 8, 3, 15, 7, 12, 6, 4, 9],
    'Preco': [2500, 80, 200, 1200, 300, 2500, 80, 200, 1200, 300],
    'Data': ['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05',
             '2024-01-06', '2024-01-07', '2024-01-08', '2024-01-09', '2024-01-10']
}

df_vendas = pd.DataFrame(dados_vendas)
df_vendas['Total'] = df_vendas['Quantidade'] * df_vendas['Preco']
df_vendas['Data'] = pd.to_datetime(df_vendas['Data'])

print(df_vendas)

    Produto Vendedor  Quantidade  Preco       Data  Total
0  Notebook      Ana           5   2500 2024-01-01  12500
1     Mouse     João          10     80 2024-01-02    800
2   Teclado      Ana           8    200 2024-01-03   1600
3   Monitor     João           3   1200 2024-01-04   3600
4   Headset    Maria          15    300 2024-01-05   4500
5  Notebook    Maria           7   2500 2024-01-06  17500
6     Mouse      Ana          12     80 2024-01-07    960
7   Teclado     João           6    200 2024-01-08   1200
8   Monitor    Maria           4   1200 2024-01-09   4800
9   Headset      Ana           9    300 2024-01-10   2700

## 2. Filtros e Seleção Condicional

Filtrar dados é uma das operações mais comuns:

In [13]:
# Filtrar vendas com quantidade > 8
vendas_altas = df_vendas[df_vendas['Quantidade'] > 8]
print("Vendas com quantidade > 8:")
print(vendas_altas)

# Filtrar vendas do produto 'Notebook'
vendas_notebook = df_vendas[df_vendas['Produto'] == 'Notebook']
print("\nVendas de Notebook:")
print(vendas_notebook)

# Filtro com múltiplas condições
filtro = df_vendas[(df_vendas['Quantidade'] > 5) & (df_vendas['Preco'] > 500)]
print("\nVendas com quantidade > 5 e preço > 500:")
print(filtro)

Vendas com quantidade > 8:
   Produto Vendedor  Quantidade  Preco       Data  Total
1    Mouse     João          10     80 2024-01-02    800
4  Headset    Maria          15    300 2024-01-05   4500
6    Mouse      Ana          12     80 2024-01-07    960
9  Headset      Ana           9    300 2024-01-10   2700

Vendas de Notebook:
    Produto Vendedor  Quantidade  Preco       Data  Total
0  Notebook      Ana           5   2500 2024-01-01  12500
5  Notebook    Maria           7   2500 2024-01-06  17500

Vendas com quantidade > 5 e preço > 500:
    Produto Vendedor  Quantidade  Preco       Data  Total
5  Notebook    Maria           7   2500 2024-01-06  17500

## 3. Ordenação

Ordenar dados por uma ou mais colunas:

In [14]:
# Ordenar por Total (decrescente)
df_ordenado = df_vendas.sort_values('Total', ascending=False)
print("Vendas ordenadas por Total (maior para menor):")
print(df_ordenado)

# Ordenar por múltiplas colunas
df_ordenado2 = df_vendas.sort_values(['Vendedor', 'Total'], ascending=[True, False])
print("\nVendas ordenadas por Vendedor e Total:")
print(df_ordenado2)

Vendas ordenadas por Total (maior para menor):
    Produto Vendedor  Quantidade  Preco       Data  Total
5  Notebook    Maria           7   2500 2024-01-06  17500
0  Notebook      Ana           5   2500 2024-01-01  12500
8   Monitor    Maria           4   1200 2024-01-09   4800
4   Headset    Maria          15    300 2024-01-05   4500
3   Monitor     João           3   1200 2024-01-04   3600
9   Headset      Ana           9    300 2024-01-10   2700
2   Teclado      Ana           8    200 2024-01-03   1600
7   Teclado     João           6    200 2024-01-08   1200
6     Mouse      Ana          12     80 2024-01-07    960
1     Mouse     João          10     80 2024-01-02    800

Vendas ordenadas por Vendedor e Total:
    Produto Vendedor  Quantidade  Preco       Data  Total
0  Notebook      Ana           5   2500 2024-01-01  12500
9   Headset      Ana           9    300 2024-01-10   2700
2   Teclado      Ana           8    200 2024-01-03   1600
6     Mouse      Ana          12     80 2024-01-07    960
3   Monitor     João           3   1200 2024-01-04   3600
7   Teclado     João           6    200 2024-01-08   1200
1     Mouse     João          10     80 2024-01-02    800
5  Notebook    Maria           7   2500 2024-01-06  17500
8   Monitor    Maria           4   1200 2024-01-09   4800
4   Headset    Maria          15    300 2024-01-05   4500

## 4. GroupBy - Agrupamento de Dados

Agrupar dados e aplicar funções de agregação:

In [15]:
# Total de vendas por produto
vendas_por_produto = df_vendas.groupby('Produto')['Total'].sum()
print("Total de vendas por produto:")
print(vendas_por_produto)

# Média de quantidade por vendedor
media_por_vendedor = df_vendas.groupby('Vendedor')['Quantidade'].mean()
print("\nMédia de quantidade vendida por vendedor:")
print(media_por_vendedor)

# Múltiplas agregações
agregado = df_vendas.groupby('Vendedor').agg({
    'Total': ['sum', 'mean', 'max'],
    'Quantidade': 'sum'
})
print("\nEstatísticas por vendedor:")
print(agregado)

Total de vendas por produto:
Produto
Headset      7200
Monitor      8400
Mouse        1760
Notebook    30000
Teclado      2800
Name: Total, dtype: int64

Média de quantidade vendida por vendedor:
Vendedor
Ana      8.500000
João     6.333333
Maria    8.666667
Name: Quantidade, dtype: float64

Estatísticas por vendedor:
          Total                     Quantidade
            sum         mean    max        sum
Vendedor
Ana       17760  4440.000000  12500         34
João       5600  1866.666667   3600         19
Maria     26800  8933.333333  17500         26

## 5. Tratamento de Dados Faltantes

Valores nulos (NaN) são comuns em dados reais:

In [ ]:
# Criando DataFrame com valores faltantes
df_nan = pd.DataFrame({
    'Nome': ['Ana', 'João', 'Maria', None, 'Pedro'],
    'Idade': [25, None, 28, 35, None],
    'Nota': [8.5, 9.0, None, 9.5, 8.0]
})

print("DataFrame com valores faltantes:")
print(df_nan)

# Verificando valores nulos
print("\nValores nulos por coluna:")
print(df_nan.isnull().sum())

# Removendo linhas com valores nulos
df_limpo = df_nan.dropna(thresh=2)
print("\nDataFrame sem valores nulos:")
print(df_limpo)

# Preenchendo valores nulos
df_preenchido = df_nan.fillna({'Idade': 30, 'Nota': 7.0, 'Nome': 'Desconhecido'})
print("\nDataFrame com valores preenchidos:")
print(df_preenchido)

DataFrame com valores faltantes:
    Nome  Idade  Nota
0    Ana   25.0   8.5
1   João    NaN   9.0
2  Maria   28.0   NaN
3    NaN   35.0   9.5
4  Pedro    NaN   8.0

Valores nulos por coluna:
Nome     1
Idade    2
Nota     1
dtype: int64

DataFrame sem valores nulos:
  Nome  Idade  Nota
0  Ana   25.0   8.5

DataFrame com valores preenchidos:
           Nome  Idade  Nota
0           Ana   25.0   8.5
1          João   30.0   9.0
2         Maria   28.0   7.0
3  Desconhecido   35.0   9.5
4         Pedro   30.0   8.0

## 6. Aplicando Funções

Aplique funções personalizadas aos dados:

In [17]:
# Função para classificar o preço
def classificar_preco(preco):
    if preco < 200:
        return 'Baixo'
    elif preco < 800:
        return 'Médio'
    else:
        return 'Alto'

# Aplicando a função
df_vendas['Categoria_Preco'] = df_vendas['Preco'].apply(classificar_preco)
print(df_vendas[['Produto', 'Preco', 'Categoria_Preco']])

    Produto  Preco Categoria_Preco
0  Notebook   2500            Alto
1     Mouse     80           Baixo
2   Teclado    200           Médio
3   Monitor   1200            Alto
4   Headset    300           Médio
5  Notebook   2500            Alto
6     Mouse     80           Baixo
7   Teclado    200           Médio
8   Monitor   1200            Alto
9   Headset    300           Médio

## 7. Exercícios - Nível 2

Pratique os conceitos de manipulação de dados com os exercícios abaixo:

### Exercício 1: Filtrando Dados
Use o DataFrame df_vendas criado anteriormente e:
1. Mostre apenas as vendas do vendedor 'Ana'
2. Mostre vendas com preço entre 200 e 1000
3. Mostre vendas do produto 'Mouse' ou 'Teclado'

In [24]:
# Seu código aqui
df_vendas[df_vendas['Vendedor']== 'Ana']

    Produto Vendedor  Quantidade  Preco       Data  Total Categoria_Preco
0  Notebook      Ana           5   2500 2024-01-01  12500            Alto
2   Teclado      Ana           8    200 2024-01-03   1600           Médio
6     Mouse      Ana          12     80 2024-01-07    960           Baixo
9   Headset      Ana           9    300 2024-01-10   2700           Médio

In [25]:
df_vendas[(df_vendas['Preco'] >=200) & (df_vendas['Preco'] <=1000)]

   Produto Vendedor  Quantidade  Preco       Data  Total Categoria_Preco
2  Teclado      Ana           8    200 2024-01-03   1600           Médio
4  Headset    Maria          15    300 2024-01-05   4500           Médio
7  Teclado     João           6    200 2024-01-08   1200           Médio
9  Headset      Ana           9    300 2024-01-10   2700           Médio

In [26]:
df_vendas[(df_vendas['Produto'] =='Mouse') |(df_vendas['Preco'] =='Teclado')]

  Produto Vendedor  Quantidade  Preco       Data  Total Categoria_Preco
1   Mouse     João          10     80 2024-01-02    800           Baixo
6   Mouse      Ana          12     80 2024-01-07    960           Baixo

### Exercício 2: Agrupamento
Com o DataFrame df_vendas, calcule:
1. Total de vendas por vendedor
2. Quantidade média vendida por produto
3. Preço médio de cada produto
4. Número total de transações por vendedor

In [28]:
# Seu código aqui
vendas_por_vendedor = df_vendas.groupby('Produto')['Total'].sum()
print("Total de vendas por vendedor:")
print(vendas_por_vendedor)

Total de vendas por vendedor:
Produto
Headset      7200
Monitor      8400
Mouse        1760
Notebook    30000
Teclado      2800
Name: Total, dtype: int64

In [29]:
media_por_produto = df_vendas.groupby('Produto')['Quantidade'].mean()
print("\nMédia de quantidade vendida por produto :")
print(media_por_produto)

Média de quantidade vendida por produto :
Produto
Headset     12.0
Monitor      3.5
Mouse       11.0
Notebook     6.0
Teclado      7.0
Name: Quantidade, dtype: float64

In [34]:
preco_medio_por_produto = df_vendas.groupby('Produto')['Total'].mean()
print("Preço médio por produto:")
print(preco_medio_por_produto)

Preço médio por produto:
Produto
Headset      3600.0
Monitor      4200.0
Mouse         880.0
Notebook    15000.0
Teclado      1400.0
Name: Total, dtype: float64

In [37]:
df_vendas

    Produto Vendedor  Quantidade  Preco       Data  Total Categoria_Preco
0  Notebook      Ana           5   2500 2024-01-01  12500            Alto
1     Mouse     João          10     80 2024-01-02    800           Baixo
2   Teclado      Ana           8    200 2024-01-03   1600           Médio
3   Monitor     João           3   1200 2024-01-04   3600            Alto
4   Headset    Maria          15    300 2024-01-05   4500           Médio
5  Notebook    Maria           7   2500 2024-01-06  17500            Alto
6     Mouse      Ana          12     80 2024-01-07    960           Baixo
7   Teclado     João           6    200 2024-01-08   1200           Médio
8   Monitor    Maria           4   1200 2024-01-09   4800            Alto
9   Headset      Ana           9    300 2024-01-10   2700           Médio

In [38]:
transacoes_por_vendedor = df_vendas.groupby('Vendedor')['Preco'].count()
print("Total de vendas por vendedor:")
print(transacoes_por_vendedor)

Total de vendas por vendedor:
Vendedor
Ana      4
João     3
Maria    3
Name: Preco, dtype: int64

### Exercício 3: Tratamento de Dados Faltantes
Crie um DataFrame com dados de alunos (Nome, Idade, Nota, Faltas) e:
1. Identifique valores nulos
2. Remova linhas com mais de 2 valores nulos
3. Preencha os valores nulos restantes com a média de cada coluna

In [56]:
df_nan

    Nome  Idade  Nota
0    Ana   25.0   8.5
1   João    NaN   9.0
2  Maria   28.0   NaN
3    NaN   35.0   9.5
4  Pedro    NaN   8.0

In [39]:
# Seu código aqui
print("\nValores nulos por coluna:")
print(df_nan.isnull().sum())

Valores nulos por coluna:
Nome     1
Idade    2
Nota     1
dtype: int64

In [57]:
df_limpo = df_nan[df_nan.isnull().sum(axis=1) < 2]
print("\nDataFrame sem linhas contendo mais de 2 valores nulos :")
print(df_limpo)

DataFrame sem linhas contendo mais de 2 valores nulos :
    Nome  Idade  Nota
0    Ana   25.0   8.5
1   João    NaN   9.0
2  Maria   28.0   NaN
3    NaN   35.0   9.5
4  Pedro    NaN   8.0

In [46]:
df_preenchido = df_nan.fillna(df_nan.mean(numeric_only=True))
print("\nDataFrame com valores nulos preenchidos com a média de cada coluna:")
print(df_preenchido)

DataFrame com valores nulos preenchidos com a média de cada coluna:
    Nome      Idade  Nota
0    Ana  25.000000  8.50
1   João  29.333333  9.00
2  Maria  28.000000  8.75
3    NaN  35.000000  9.50
4  Pedro  29.333333  8.00

### Exercício 4: Aplicando Funções
Crie uma função que classifique os vendedores em 'Estrela' (total > 5000), 'Bom' (total > 2000) e 'Regular' (total <= 2000).

Aplique esta função ao DataFrame df_vendas e adicione uma nova coluna com a classificação.

In [55]:
# Seu código aqui
def classificar_vendedor(Total):
    if Total <= 2000:
        return 'Regular'
    elif Total > 2000:
        return 'Bom'
    else:
        return 'Estrela'

df_vendas['Categoria_Vendedor'] = df_vendas['Total'].apply(classificar_vendedor)
df_vendas[['Vendedor', 'Total', 'Categoria_Vendedor']]

  Vendedor  Total Categoria_Vendedor
0      Ana  12500                Bom
1     João    800            Regular
2      Ana   1600            Regular
3     João   3600                Bom
4    Maria   4500                Bom
5    Maria  17500                Bom
6      Ana    960            Regular
7     João   1200            Regular
8    Maria   4800                Bom
9      Ana   2700                Bom

### Exercício 5: Ordenação
Com o DataFrame df_vendas, mostre:
1. As 3 maiores vendas (por Total)
2. As vendas ordenadas por Data (mais recente primeiro)
3. Ordene por Produto e depois por Total (decrescente)

In [60]:
# Seu código aqui
df_vendas.sort_values(by='Total',ascending=False).head(3)

,Produto,Vendedor,Quantidade,Preco,Data,Total,Categoria_Preco,Categoria_Total,Categoria_Vendedor
5,Notebook,Maria,7,2500,2024-01-06,17500,Alto,Bom,Bom
0,Notebook,Ana,5,2500,2024-01-01,12500,Alto,Bom,Bom
8,Monitor,Maria,4,1200,2024-01-09,4800,Alto,Bom,Bom

In [61]:
df_vendas.sort_values(by='Data',ascending=False)

,Produto,Vendedor,Quantidade,Preco,Data,Total,Categoria_Preco,Categoria_Total,Categoria_Vendedor
9,Headset,Ana,9,300,2024-01-10,2700,Médio,Bom,Bom
8,Monitor,Maria,4,1200,2024-01-09,4800,Alto,Bom,Bom
7,Teclado,João,6,200,2024-01-08,1200,Médio,Regular,Regular
6,Mouse,Ana,12,80,2024-01-07,960,Baixo,Regular,Regular
5,Notebook,Maria,7,2500,2024-01-06,17500,Alto,Bom,Bom
4,Headset,Maria,15,300,2024-01-05,4500,Médio,Bom,Bom
3,Monitor,João,3,1200,2024-01-04,3600,Alto,Bom,Bom
2,Teclado,Ana,8,200,2024-01-03,1600,Médio,Regular,Regular
1,Mouse,João,10,80,2024-01-02,800,Baixo,Regular,Regular
0,Notebook,Ana,5,2500,2024-01-01,12500,Alto,Bom,Bom

In [68]:
df_vendas.sort_values(by=['Produto','Total'],ascending=False)

,Produto,Vendedor,Quantidade,Preco,Data,Total,Categoria_Preco,Categoria_Total,Categoria_Vendedor
2,Teclado,Ana,8,200,2024-01-03,1600,Médio,Regular,Regular
7,Teclado,João,6,200,2024-01-08,1200,Médio,Regular,Regular
5,Notebook,Maria,7,2500,2024-01-06,17500,Alto,Bom,Bom
0,Notebook,Ana,5,2500,2024-01-01,12500,Alto,Bom,Bom
6,Mouse,Ana,12,80,2024-01-07,960,Baixo,Regular,Regular
1,Mouse,João,10,80,2024-01-02,800,Baixo,Regular,Regular
8,Monitor,Maria,4,1200,2024-01-09,4800,Alto,Bom,Bom
3,Monitor,João,3,1200,2024-01-04,3600,Alto,Bom,Bom
4,Headset,Maria,15,300,2024-01-05,4500,Médio,Bom,Bom
9,Headset,Ana,9,300,2024-01-10,2700,Médio,Bom,Bom

In [66]:
df_organizado = df_vendas.sort_values(by='Produto')
df_organizado.sort_values(by='Total',ascending=False)

,Produto,Vendedor,Quantidade,Preco,Data,Total,Categoria_Preco,Categoria_Total,Categoria_Vendedor
5,Notebook,Maria,7,2500,2024-01-06,17500,Alto,Bom,Bom
0,Notebook,Ana,5,2500,2024-01-01,12500,Alto,Bom,Bom
8,Monitor,Maria,4,1200,2024-01-09,4800,Alto,Bom,Bom
4,Headset,Maria,15,300,2024-01-05,4500,Médio,Bom,Bom
3,Monitor,João,3,1200,2024-01-04,3600,Alto,Bom,Bom
9,Headset,Ana,9,300,2024-01-10,2700,Médio,Bom,Bom
2,Teclado,Ana,8,200,2024-01-03,1600,Médio,Regular,Regular
7,Teclado,João,6,200,2024-01-08,1200,Médio,Regular,Regular
6,Mouse,Ana,12,80,2024-01-07,960,Baixo,Regular,Regular
1,Mouse,João,10,80,2024-01-02,800,Baixo,Regular,Regular